# 文件上传路径
file:
  upload-dir: D:/WEB_YQG_STATIC/

# 服务器配置
server:
  port: 8081
  tomcat.uri-encoding: UTF-8
#  servlet:
#    context-path: /Https
#    # https
#    ssl:
#      key-store: classpath:yqg_https_key   #??
#      key-alias: https
#      key-store-password: 654399

# MyBatis配置
mybatis:
  type-aliases-package: com.yqg.vo
  # 是否开启驼峰命名
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# RabbitMQ配置
spring:
  rabbitmq:
    host: localhost
    username: yqg
    password: 123456
    port: 5672
    virtual-host: yqghost

  # 邮件配置
  mail:
    port: 587
    # 协议 默认就是smtp 使用465端口改成smtps
    protocol: smtp
    host: smtp.qq.com
    # 使用其他邮箱port与host配置可能不同，密码有的还可以是授权码
    username: 3300303281@qq.com
    password: qlyutpbkgygddcaa
    default-encoding: UTF-8
    # 自定义配置，邮件发送人，昵称
    nickname: 猿趣阁
    debug: true
    # 设置开启ssl
    properties:
      mail:
        stmp:
          ssl:
            enable: true

  main:
    allow-bean-definition-overriding: true

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_yqg?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    druid:
      # 初始化连接数
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 连接等待超时时间
      maxWait: 60000
      # 连接间隔检测时间
      timeBetweenEvictionRunsMillis: 60000
      # 连接空闲释放时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # PSCache开启，同时开启preparedStatment的池管理
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置过滤器
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      # 配置DruidStatFilter
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  # Redis配置
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      timeout: 20000
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
      password:

  # Web资源配置
  web:
    resources:
      static-locations: classpath:/image/,classpath:/text/,classpath:/video/,classpath:/audio/,classpath:/compressed/

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl